apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pibot.name" . }}
type: Opaque
stringData:
  DISCORD_TOKEN: {{ .Values.discord.token | quote }}
  MONGODB_URI: {{ .Values.mongodb.uri | quote }}
  DEEPL_API_KEY: {{ .Values.deepl.apiKey | quote }}
  {{- if .Values.environment }}
  ENVIRONMENT: {{ .Values.environment | quote }}
  {{- end }}
